version: '3.5'

services:
  yolcu360:
    image: yolcuapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - yolcu360network
    depends_on:
      - database
    environment:
      'DB_STRING': 'host=database user=postgres password=postgres dbname=yolcu360 port=5432 sslmode=disable'
     

  database:
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=yolcu360
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - yolcu360network

networks:
  yolcu360network:
    driver: bridge

volumes:
  data:
    driver: local
