// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/locations/active": {
            "get": {
                "description": "List all active locations",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "locations"
                ],
                "summary": "List active locations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessfullActiveLocations"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Error"
                        }
                    }
                }
            }
        },
        "/reservations": {
            "post": {
                "description": "Send reservation request for a car if its successfull then car is reserved to the given user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reservations"
                ],
                "summary": "Reserve an available car",
                "parameters": [
                    {
                        "description": "Reserve a car",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CarReservationModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessfullReservation"
                        }
                    },
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/models.Error"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Error"
                        }
                    }
                }
            }
        },
        "/reservations/all": {
            "get": {
                "description": "List all reservations in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reservations"
                ],
                "summary": "List all reservations in the system",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessfullAllReservations"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Error"
                        }
                    }
                }
            }
        },
        "/reservations/lookup": {
            "post": {
                "description": "Get available cars with the given parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reservations"
                ],
                "summary": "Get available cars",
                "parameters": [
                    {
                        "description": "Get available cars",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CarAvailabilityIdentifier"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessfullAvailableCars"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Car": {
            "type": "object",
            "required": [
                "fuel",
                "name",
                "office_id",
                "transmission"
            ],
            "properties": {
                "fuel": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 2
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 2
                },
                "office_id": {
                    "type": "integer"
                },
                "transmission": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 2
                }
            }
        },
        "models.CarAvailabilityIdentifier": {
            "type": "object",
            "properties": {
                "location_id": {
                    "type": "integer"
                },
                "reservation_begin": {
                    "type": "string"
                },
                "reservation_end": {
                    "type": "string"
                }
            }
        },
        "models.CarReservationModel": {
            "type": "object",
            "required": [
                "car_id",
                "leaser_id",
                "location_id",
                "reservation_begin",
                "reservation_end"
            ],
            "properties": {
                "car_id": {
                    "type": "integer"
                },
                "leaser_id": {
                    "type": "integer"
                },
                "location_id": {
                    "type": "integer"
                },
                "reservation_begin": {
                    "type": "string"
                },
                "reservation_end": {
                    "type": "string"
                }
            }
        },
        "models.CarsReservation": {
            "type": "object",
            "required": [
                "car_id",
                "leaser_id",
                "location_id",
                "reservation_begin",
                "reservation_end"
            ],
            "properties": {
                "car_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "leaser_id": {
                    "type": "integer"
                },
                "location_id": {
                    "type": "integer"
                },
                "reservation_begin": {
                    "type": "string"
                },
                "reservation_end": {
                    "type": "string"
                }
            }
        },
        "models.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.LocationIdentifier": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.SuccessfullActiveLocations": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.LocationIdentifier"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.SuccessfullAllReservations": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CarsReservation"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.SuccessfullAvailableCars": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Car"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.SuccessfullReservation": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.CarReservationModel"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "RentACar Yolcu360 Case",
	Description:      "This is RentACarAPI documentation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
